// src/components/StartActions.jsx
import { TOOLTIP_ID } from '../constants.js';
import styles from './StartActions.module.scss';

function clearCache() {
  window.localStorage.clear();
  window.location.reload();
}

const actions = [
  {
    name: 'Clear Cache',
    action: clearCache,
    icon: 'fa-shower',
    tooltip: 'Clean Caches',
  },
];

export default function StartActions() {
  return (
    <div className={styles.actions}>
      {actions
        .filter((action) => action.icon)
        .map((action) => (
          <button
            key={action.name}
            type="button"
            aria-label={action.name}
            className={styles.action}
            onClick={action.action}
            data-tooltip-id={TOOLTIP_ID}
            data-tooltip-content={action.tooltip}
            data-tooltip-place="top-start"
          >
            <i className={`fa ${action.icon}`} />
          </button>
        ))}
    </div>
  );
}

// src/components/StartActions.vue
<template>
  <div v-if="logo" class="startmenu__actions" >
    <i v-for="action in actions" v-if="action.icon" :key="action.name" @click="action.action" :class="[action.icon, 'fa']"  v-tooltip.top-start="action.tooltip"></i>
  </div>
</template>

<script>
export default {
  name: 'start-button',
  data() {
    return {
      logo: 'true',
      actions: [
        {
          name: 'Clear Cache',
          action: this.clearCache,
          icon: 'fa-shower',
          tooltip: 'Clean Caches',
        },
      ],
    };
  },
  methods: {
    fire() {
      this.$parent.$parent.toggleResume();
    },
    clearCache() {
      window.localStorage.clear();
      window.location.reload();
    },
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style  lang="scss">
.startmenu__actions {
  display: flex;
  align-items: center;
  padding-right: 1rem;
  > i {
    color: white;
    font-size: 1.5rem;
  }
}
</style>
